function ScriptPython = CorrectRater_Python(obj, PathR, NoData)

if isunix
    ScriptPython = @(PathR) ['import rasterio',newline,...
            'Path_Raster = r"',PathR,'"',newline,...
            'Tmp     = rasterio.open(Path_Raster)',newline,...
            'Data    = Tmp.read(1)',newline,...
            'height  = Tmp.shape[0]',newline,...
            'width   = Tmp.shape[1]',newline,...
            'crs     = Tmp.crs',newline,...
            'transform = Tmp.transform',newline,...
            'Tmp.close()',newline,...
            'with rasterio.open(',newline,...
            '    Path_Raster,"w",',newline,...
            '    driver="GTiff",',newline,...
            '    height=height,',newline,...
            '    width=width,',newline,...
            '    count=1,',newline,...
            '    dtype=Data.dtype,',newline,...
            '    crs=crs,',newline,...
            '    transform=transform,',newline,...
            '    nodata= ',num2str(NoData),newline,...
            ') as dst:',newline,...
            '    dst.write(Data, 1)'];
else
    ScriptPython = @(PathR) ['import rasterio',newline,...
            'Path_Raster = r"',PathR,'"',newline,...
            'Tmp     = rasterio.open(Path_Raster)',newline,...
            'Data    = Tmp.read(1)',newline,...
            'height  = Tmp.shape[0]',newline,...
            'width   = Tmp.shape[1]',newline,...
            'crs     = Tmp.crs',newline,...
            'transform = Tmp.transform',newline,...
            'Tmp.close()',newline,...
            'with rasterio.open(',newline,...
            '    Path_Raster,"w",',newline,...
            '    driver="GTiff",',newline,...
            '    height=height,',newline,...
            '    width=width,',newline,...
            '    count=1,',newline,...
            '    dtype=Data.dtype,',newline,...
            '    crs=crs,',newline,...
            '    transform=transform,',newline,...
            '    nodata= ',num2str(NoData),newline,...
            ') as dst:',newline,...
            '    dst.write(Data, 1)'];
end

%%
NameFile    = strrep(PathR,'\','\\');
NewScript   = ScriptPython(NameFile);

%% Save New BasinFile    
NameFile = fullfile(obj.PathProject,'Script_Python.py');
ID_File = fopen(NameFile, 'w');
fprintf(ID_File, NewScript);
fclose(ID_File);                        

system(['conda activate Matlab && python "',fullfile(obj.PathProject,'Script_Python.py"')]);
